export const SYS_FONTS = [
  { label: 'Arial', value: 'Arial' },
  { label: 'Microsoft Yahei', value: 'Microsoft Yahei' },
  { label: 'SimSun', value: 'SimSun' },
  { label: 'SimHei', value: 'SimHei' },
  { label: 'KaiTi', value: 'KaiTi' },
  { label: 'NSimSun', value: 'NSimSun' },
  { label: 'FangSong', value: 'FangSong' },
  { label: 'PingFang SC', value: 'PingFang SC' },
  { label: 'STHeiti', value: 'STHeiti' },
  { label: 'STKaiti', value: 'STKaiti' },
  { label: 'STSong', value: 'STSong' },
  { label: 'STFangSong', value: 'STFangSong' },
  { label: 'STZhongSong', value: 'STZhongSong' },
  { label: 'STHupo', value: 'STHupo' },
  { label: 'STXinwei', value: 'STXinwei' },
  { label: 'STLiti', value: 'STLiti' },
  { label: 'STXingkai', value: 'STXingkai' },
  { label: 'Hiragino Sans GB', value: 'Hiragino Sans GB' },
  { label: 'Lantinghei SC', value: 'Lantinghei SC' },
  { label: 'Hanzipen SC', value: 'Hanzipen SC' },
  { label: 'Hannotate SC', value: 'Hannotate SC' },
  { label: 'Songti SC', value: 'Songti SC' },
  { label: 'Wawati SC', value: 'Wawati SC' },
  { label: 'Xingkai SC', value: 'Xingkai SC' },
  { label: 'Yuanti SC', value: 'Yuanti SC' },
  { label: 'STXihei', value: 'STXihei' },
  { label: 'YouYuan', value: 'YouYuan' },
  { label: 'LiSu', value: 'LiSu' },
]

export const WEB_FONTS = [
  { label: 'De Yi Black', value: 'De Yi Black' },
  { label: 'Cang Er Xiao Wan Zi', value: 'Cang Er Xiao Wan Zi' },
  { label: 'You Design Title Black', value: 'You Design Title Black' },
  { label: 'Peak Guangming Rui Ti', value: 'Peak Guangming Rui Ti' },
  { label: 'Shetu Modern Small Square Body', value: 'Shetu Modern Small Square Body' },
  { label: 'ZCOOL Happy', value: 'ZCOOL Happy' },
  { label: 'Character Zone Ximai Body', value: 'Character Zone Ximai Body' },
  { label: 'Material Market Kangkang Body', value: 'Material Market Kangkang Body' },
  { label: 'Material Market Cool Square Body', value: 'Material Market Cool Square Body' },
  { label: 'Tuniu Type Yuan Body', value: 'Tuniu Type Yuan Body' },
  { label: 'Rui Zi Zhen Yan Body', value: 'Rui Zi Zhen Yan Body' },
]
